callsign = "K7SKJ"
operator-name = "Simon Johnston"
default-station = 0

[[stations]]
kind = "Home"
label = "My home/primary location"

[stations.location]
grid-locator = "CN87wo"
country = "US"

[locale]
length_units = "imperial"
temperature_units = "imperial"
time_format = "military"

[[equipment]]
brand = "Icom"
model = "705"
label = "IC-705"
usage = [
    "Local",
    "DX",
    "QRP",
]
modes = [
    "FM",
    "Digital",
    "SSB",
]
mobility = "StationFixed"
bands = [
    "HF",
    "VHF",
    "UHF",
]
max-power = 10.0

[services]
storage_kind = "plain-text"

[services.credentials.qrz-api]
identifier = "K7SKJ"
secret = "hhzz"
