[package]
name = "rfham-bands"
description = "Data types to represent band plans."
version = "0.1.1"
readme = "README.md"
publish = true

edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
features = ["std"]
rustdoc-args = ["--generate-link-to-definition"]

[package.metadata.playground]
features = ["std"]

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_json/std",
    "serde_with/std",
    "thiserror/std",
    "uom/std",
    "colored",
]
no-color = ["std", "colored/no-color"]

[dependencies]
rfham-core = { version = "0.1.1", path = "../rfham-core" }
rfham-itu = { version = "0.1.2", path = "../rfham-itu" }
rfham-markdown = { version = "0.1.1", path = "../rfham-markdown" }

colored = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
uom = { workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies.wasm-bindgen-test]
version = "0.3"

[lints]
workspace = true
