[package]
name = "rfham-rigs"
description = "Rig data and control"
version = "0.1.1"
readme = "README.md"
publish = true

edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["transport", "protocol", "elecraft"]

## Enables the transport layer.
transport = ["tr-serial", "tr-ip"]

## Enables the serial port transport layer.
tr-serial = ["serialport"]

## Enables the TCP/IP transport layer.
tr-ip = []

## Enables the protocol layer.
protocol = ["proto-cat", "proto-civ"]

## Enables *all* supported CAT-like implementations.
proto-cat = ["elecraft"]

## Enables *all* supported Elecraft transceivers, tuners, amplifiers, and panadapters.
elecraft = [
    # Transceivers
    "k2-kio2",
    "k3-kx",
    "k4",
    "kh1",
    # Tuners
    "kat500",
    # Amplifiers
    "kpa500",
    "kpa1500",
    "kxpa100",
    # Panadapters
    "p3",
    "px3",
]

## Enable the Elecraft K2 transceiver family, using the KIO2 interface.
k2-kio2 = []

## Enable the Elecraft K3/KX transceiver families; requires *k2-kio2*.
k3-kx = ["k2-kio2"]

## Enable the Elecraft K4 transceiver family; requires *k3-kx*.
k4 = ["k3-kx"]

## Enable the Elecraft KH1 transceiver family.
kh1 = []

## Enable the Elecraft KAT500 automatic antenna tuner.
kat500 = []

## Enable the Elecraft KPA500 linear amplifier.
kpa500 = []

## Enable the Elecraft KPA1500 linear amplifier.
kpa1500 = []

## Enable the Elecraft KXPA100 linear amplifier.
kxpa100 = []

## Enable the Elecraft P3 panadapter.
p3 = []

## Enable the Elecraft PX3 panadapter.
px3 = []

## Enables *all* supported CI-V implementations.
proto-civ = []

## Enables *all* supported Icom transceivers, tuners, and amplifiers.
icom = ["ic-705"]

## Enable the Icom IC-705 transceiver.
ic-705 = []

## Enables *all* supported Xiegu transceivers, tuners, and amplifiers.
xiegu = []

## Enables *all* supported Kenwood transceivers, tuners, and amplifiers.
kenwood = []

## Enables *all* supported Yaesu transceivers, tuners, and amplifiers.
yaesu = []

## For the high-level entity API.
entity-api = []

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = [
    "alloc",
    "clock",
    "now",
] }
document-features = "0.2"
num = "0.4"
pastey = "0.2.3"
rfham-config = { version = "0.1.1", path = "../rfham-config" }
rfham-core = { version = "0.1.1", path = "../rfham-core" }
rfham-iri = { version = "0.1.0", path = "../rfham-iri" }
rfham-itu = { version = "0.1.2", path = "../rfham-itu" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serialport = { version = "4.9.0", features = ["serde"], optional = true }
strum = { version = "0.28", features = ["derive"] }
thiserror = { version = "2.0", default-features = false }
toml = { version = "1.1.3", features = ["serde"] }
tracing = "0.1.44"

[dev-dependencies]
pretty_assertions = "1.4"

[lints]
workspace = true
