[package]
name = "rfham-markdown"
description = "Markdown writer (utility) for RF-Ham libraries."
version = "0.1.1"
readme = "README.md"
publish = true

edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
features = ["std"]
rustdoc-args = ["--generate-link-to-definition"]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["std"]
std = ["colored"]
no-color = ["std", "colored/no-color"]

[dependencies]
colored = { version = "3.1", optional = true }
thiserror = { version = "2.0", default-features = false }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies.wasm-bindgen-test]
version = "0.3"

[lints]
workspace = true
