[package]
name = "rfham-iri"
description = "Support the rfham URN/IRI scheme"
version = "0.1.0"
publish = true

edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["std", "serde"]
#! This library supports `no_std` if you set `default-features` to `false`.

## Use the standard library global heap allocator, required whether you use `std` or `no_std`.
alloc = []

## This feature adds Serde support for serialization of the URN type.
serde = ["dep:serde", "alloc"]

## Enables the `std` library, and associated feature in dependencies.
std = ["serde?/std"]

[dependencies]
rfham-core = { version = "0.1.1", path = "../rfham-core" }

document-features = { workspace = true }
serde = { workspace = true, optional = true }
strum = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
