[package]
name = "rfham-config"
description = "Shared configuration data for RF-Ham libraries and tools."
version = "0.1.1"
readme = "README.md"
publish = true

edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rfham-bands = { version = "0.1.1", path = "../rfham-bands" }
rfham-core = { version = "0.1.1", path = "../rfham-core" }
rfham-geo = { version = "0.1.1", path = "../rfham-geo" }
rfham-itu = { version = "0.1.2", path = "../rfham-itu" }
rfham-maidenhead = { version = "0.1.0", path = "../rfham-maidenhead" }
rfham-markdown = { version = "0.1.1", path = "../rfham-markdown" }

language-tags = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serialport = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

xdirs = "0.1"

[dev-dependencies]
pretty_assertions = "1.4"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies.wasm-bindgen-test]
version = "0.3"

[lints]
workspace = true
