[package]
name = "rfham-maidenhead"
version = "0.1.0"
edition = "2024"
description = "Implementation of Grid traits for Maidenhead locator system."
license = "MIT OR Apache-2.0"
keywords = ["ham", "radio"]
readme = "README.md"
# Minimum Supported Rust Version
rust-version = "1.94"


[package.metadata.docs.rs]
features = ["std"]
rustdoc-args = ["--generate-link-to-definition", "--html-in-header", "rustdoc/header.html"]

[package.metadata.playground]
features = ["std"]

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies.wasm-bindgen-test]
version = "0.3"

[features]
default = ["std"]
std = []

[dependencies]
rfham-core = { version = "0.1.1", path = "../rfham-core" }
rfham-geo = { version = "0.1.1", path = "../rfham-geo" }

document-features = { workspace = true }
lat-long = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"

[lints]
workspace = true
